// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2I57d4A3SQCpoLdbQwMx8J9QZW8uDV4Q',
    appId: '1:720244504148:web:1c0def99193afb23cc1fc1',
    messagingSenderId: '720244504148',
    projectId: 'fir-pro-87705',
    authDomain: 'fir-pro-87705.firebaseapp.com',
    storageBucket: 'fir-pro-87705.firebasestorage.app',
    measurementId: 'G-5NCRK16M0F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACqHjxULjPNg0bu7QFdE3EYcRuAq0EGVc',
    appId: '1:720244504148:android:daf0edb353b3fc8dcc1fc1',
    messagingSenderId: '720244504148',
    projectId: 'fir-pro-87705',
    storageBucket: 'fir-pro-87705.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkgrQMe_BREFDAgn_KTNfFlTGyYLQPILA',
    appId: '1:720244504148:ios:178bcce08ebb2b53cc1fc1',
    messagingSenderId: '720244504148',
    projectId: 'fir-pro-87705',
    storageBucket: 'fir-pro-87705.firebasestorage.app',
    iosBundleId: 'com.example.gangoliShivalya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkgrQMe_BREFDAgn_KTNfFlTGyYLQPILA',
    appId: '1:720244504148:ios:178bcce08ebb2b53cc1fc1',
    messagingSenderId: '720244504148',
    projectId: 'fir-pro-87705',
    storageBucket: 'fir-pro-87705.firebasestorage.app',
    iosBundleId: 'com.example.gangoliShivalya',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2I57d4A3SQCpoLdbQwMx8J9QZW8uDV4Q',
    appId: '1:720244504148:web:96b44edfb25e97c8cc1fc1',
    messagingSenderId: '720244504148',
    projectId: 'fir-pro-87705',
    authDomain: 'fir-pro-87705.firebaseapp.com',
    storageBucket: 'fir-pro-87705.firebasestorage.app',
    measurementId: 'G-LJEXTCN4XH',
  );
}
